# Generated by Django 3.0.8 on 2020-07-08 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Проект',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('наименование_устройства', models.CharField(max_length=100)),
            ],
        ),
    ]
