# Generated by Django 3.0.8 on 2020-07-08 12:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Организация', '0001_initial'),
        ('Проект', '0002_auto_20200708_1454'),
    ]

    operations = [
        migrations.AddField(
            model_name='проект',
            name='заказчик',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, to='Организация.Организация'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='проект',
            name='код',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='проект',
            name='краткое_наименование',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='проект',
            name='шифр',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
