# Generated by Django 3.0.8 on 2020-07-08 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Разрешение',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('выбор_типа', models.CharField(choices=[('1', 'Лицензии'), ('2', 'Свидетельства'), ('3', 'Аттестаты аккредитации'), ('4', 'Сертификаты соответствия'), ('5', 'Санитарно-эпидемиологические заключения'), ('6', 'Экспертные заключения'), ('7', 'СРО')], max_length=1)),
                ('серия_номер', models.CharField(max_length=20)),
                ('кем_выдан', models.CharField(max_length=100)),
                ('описание', models.TextField()),
                ('дата_выдачи', models.DateField()),
                ('срок_окончания', models.DateField()),
            ],
            options={
                'verbose_name': 'Разрешение',
                'verbose_name_plural': 'Разрешения',
            },
        ),
    ]
