# Generated by Django 3.0.8 on 2020-07-08 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Разрешение', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='разрешение',
            old_name='серия_номер',
            new_name='серия_и_номер',
        ),
        migrations.AlterField(
            model_name='разрешение',
            name='выбор_типа',
            field=models.CharField(choices=[('1', 'Лицензия'), ('2', 'Свидетельство'), ('3', 'Аттестат аккредитации'), ('4', 'Сертификат соответствия'), ('5', 'Санитарно-эпидемиологическое заключение'), ('6', 'Экспертное заключение'), ('7', 'СРО')], max_length=1),
        ),
    ]
