# Generated by Django 3.0.8 on 2020-07-08 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Персона', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='персона',
            options={'verbose_name': 'Персона', 'verbose_name_plural': 'Персонал'},
        ),
    ]
