# Generated by Django 3.0.8 on 2020-07-08 11:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Разрешение', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Организация',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('наименование', models.CharField(max_length=100)),
                ('директор', models.CharField(max_length=100)),
                ('руководитель', models.CharField(max_length=100)),
                ('исполнитель', models.CharField(max_length=100)),
                ('согласователь', models.CharField(max_length=100)),
                ('разрешения', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Разрешение.Разрешение')),
            ],
            options={
                'verbose_name': 'Организация',
                'verbose_name_plural': 'Организации',
            },
        ),
    ]
