# Generated by Django 3.0.8 on 2020-07-08 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Разрешение', '0002_auto_20200708_1454'),
        ('Организация', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='организация',
            name='разрешения',
        ),
        migrations.AddField(
            model_name='организация',
            name='разрешения',
            field=models.ManyToManyField(to='Разрешение.Разрешение'),
        ),
    ]
